/**
 * HappinessSystem – Civ 1-style city happiness model.
 *
 * Happiness categories (per Civ1 manual):
 *   Happy citizens    – generated by luxuries.  Offset unhappy citizens 1-for-1.
 *   Content citizens  – neither happy nor unhappy. Born content up to the
 *                       difficulty-adjusted base; also produced by temples,
 *                       colosseums, cathedrals, and martial law.
 *   Unhappy citizens  – citizens beyond the content base, plus military-away
 *                       penalties (Republic/Democracy).
 *
 * Disorder: a city is in disorder when unhappyCitizens > happyCitizens.
 * Civil disorder for 2+ consecutive turns can topple Republic/Democracy
 * governments (see TurnManager.checkGovernmentDisorderCollapse).
 */

import { BuildingType, GOVERNMENTS, type City, type GameState, type Player } from '../types/game';
import { getDifficultyParams } from './DifficultyConfig';
import { TaxSystem } from './TaxSystem';
import { BUILDING_DEFINITIONS } from './BuildingDefinitions';
import { getUnitStats } from './UnitDefinitions';

export interface CityHappinessResult {
  happyCitizens: number;
  unhappyCitizens: number;
  contentCitizens: number;
  inDisorder: boolean;
}

export class HappinessSystem {
  /**
   * Compute the full happiness breakdown for a single city this turn.
   *
   * Processing order (mirrors Civ1):
   *   1. Base content/unhappy split (population vs difficulty contentCitizensBase)
   *   2. Unhappiness from military units away from home (Republic: ×1, Democracy: ×2)
   *   3. Martial law: military units garrisoned in the city suppress unhappiness
   *      (Despotism / Monarchy / Communism only; max 3 units)
   *   4. Building happyFaces bonuses convert unhappy → content
   *      (Temple +1, Colosseum +3, Cathedral +4)
   *   5. Luxury income: every 2 luxury points → 1 happy citizen
   *      (includes entertainer specialists via TaxSystem)
   *   6. Disorder check: inDisorder = unhappyCitizens > happyCitizens
   */
  public static calculateCityHappiness(
    city: City,
    player: Player,
    gameState: GameState
  ): CityHappinessResult {
    const isAI = !player.isHuman;
    const params = getDifficultyParams(gameState.difficulty ?? 'chieftain');
    const gov = GOVERNMENTS[player.government];

    // ── Step 1: base content / unhappy split ──────────────────────────────
    // AI players get a happiness bonus so they don't constantly collapse.
    const contentBase = isAI
      ? params.contentCitizensBase + params.aiHappinessBonus
      : params.contentCitizensBase;

    // Citizens beyond the content base start as unhappy.
    let unhappy = Math.max(0, city.population - contentBase);

    // ── Step 2: military-away unhappiness (Republic / Democracy) ─────────
    const awayPenalty = gov.effects.unhappinessFromMilitary; // 0 for most govts
    if (awayPenalty > 0) {
      const playerCities = gameState.cities.filter(c => c.playerId === player.id);
      const cityPositionSet = new Set(playerCities.map(c => `${c.position.x},${c.position.y}`));

      // Military unit = any unit with attack > 0 or defense > 0 that is NOT
      // standing in one of the player's own cities.
      const awayMilitary = gameState.units.filter(u => {
        if (u.playerId !== player.id) return false;
        if (cityPositionSet.has(`${u.position.x},${u.position.y}`)) return false;
        const stats = getUnitStats(u.type);
        return stats.attack > 0 || stats.defense > 0;
      });

      // Since we have no home-city tracking, spread the unhappiness evenly
      // across all player cities (rounding up per city so nothing is lost).
      const cityCount = Math.max(1, playerCities.length);
      unhappy += Math.ceil((awayMilitary.length * awayPenalty) / cityCount);
    }

    // ── Step 3: martial law (Despotism / Monarchy / Communism) ───────────
    // Each defensive military unit garrisoned in this city suppresses 1
    // unhappy citizen (up to a maximum of 3 units).
    if (gov.effects.martialLawAvailable) {
      const garrisoned = gameState.units.filter(u => {
        if (u.playerId !== player.id) return false;
        if (u.position.x !== city.position.x || u.position.y !== city.position.y) return false;
        const stats = getUnitStats(u.type);
        return stats.defense > 0; // must be a defensive military unit
      });
      const suppressed = Math.min(3, garrisoned.length);
      unhappy = Math.max(0, unhappy - suppressed);
    }

    // ── Step 4: building happyFaces bonuses (convert unhappy → content) ──
    for (const building of city.buildings) {
      if (unhappy <= 0) break;
      const def = BUILDING_DEFINITIONS[building.type as BuildingType];
      if (def?.effects?.happyFaces) {
        unhappy = Math.max(0, unhappy - def.effects.happyFaces);
      }
    }

    // ── Step 5: luxury income → happy citizens ────────────────────────────
    // Uses TaxSystem to get the real luxury output for this city (includes
    // Marketplace/Bank multipliers and entertainer specialists).
    // Every 2 luxury points → 1 happy citizen (Civ1 rule).
    const taxBreakdown = TaxSystem.calculateCityTaxBreakdown(city, player, gameState);
    const happy = Math.floor(taxBreakdown.totalLuxury / 2);

    // ── Step 6: disorder check ─────────────────────────────────────────────
    const inDisorder = unhappy > happy;
    const contentCitizens = Math.max(0, city.population - happy - unhappy);

    return { happyCitizens: happy, unhappyCitizens: unhappy, contentCitizens, inDisorder };
  }
}
